

-------------------------------------------------------------------------------------------------------------------------
//My first Java Program 


public class App {           // must be capital S 
	public static void main (String[] args) {
				// voide = no return type  //name of string array is called args 
	System.out.println("Hey"); }
	
}


-------------------------------------------------------------------------------------------------------------------------

//variables in Java 

// <define variable type> <name of variable> = <value of variable> //

String characterName = "Tom"; //String
int characterAge = 40; //Integer 

// We can access variable names 

System.out.println("There once was a man named" + characterName); //insert like this in the beginning and end


// you can insert the variable in the middle of a line of text 

System.out.println("The name of the man " + characterName + "but he didnt like his name"); 


--------------------------------------------------------------------------------------------------------------------------
