
// for loops in Java // 


// uses an indexing variable to keep track of how many times we loop through 

/* Basic strucure for our for loop:

	for ( <define index variable>; <Condition to keep going>;  <incrementing>)   //no semi color at end of it 


*/ 


public class App {
	
	public static void main(String[] args) {
		
		for (int =1;  i <=10; i++) { 
		
		System.out.println(i); 
		
		} 

	}
} 
	


// we can use for loop to loop through array of strings 


public class App {
	
	public static void main(String[] args) {

		String [] friends = { "Jim", "Angela", "Oscar"}; 

			for (int i = 0; i < friends.length; i++) {
	
			System.out.println(friends[i]); } 
			
	}
}

