
/* Static Methods inside of classes 

	- can be accessed from inside of class without creating an instance of that class 
	
	- we can also create a class that has static methods and we can access the methods wherever we want
	without creating instances of the class */ 
	
	public class App {
		
		public static void main(String[] args) {
			
			System.out.println(Math.max(3,6); // output will be 6 

				// the math class is storing static methods 
				
				// method we can use without creating an instance of that class 
				
				// we dont need the folllowing 
				
				math newMath = new Math(); 
				
		} 
	} 
	} 
	
	
	// creating a new class with static methods 
	
	public class Prints {
		
		public static void sayGoodbye() {
			System.out.println("Goodbye!"); } 
			
	
	} 
	
	
	// in the main method - we can just now access it directly 
	
	
	public class App {
		
		public static void main(String[] args) {
			
			Prints.sayGoodbye(); } 
			
			/* we just directly accessed it, we didnt need to do
			
			"Prints myprints = new Prints() */ 
	
	
	
	} 
	
	
	// classes can be used for methods, attributes. not only for storing variables. 
