
/* Access Modifiers*/ 

/* 

Acess modifiers are key words we can give to our entities in our java program, things like variables and
it basically controls what other entities inside our program can access them 

Control what other entities can access the object 


// public - Anything can access it 

	> Any other entities within Java can access this class 
	
	> if you dont care who has access to your class, you can go ahead and throw it on there. 



// private - Only accessable from inside its own class 

	> This entinty can only be accessed by things inside its own class 
	> allow people to access them using getters and setters that are public 




// protected - only accessed by other java classes and objects inside the same package 

- 


*/ 




public class App {
	
	public static void main (Strings[] args) {
		
		
		Song Hoilday = new Song("Hoilday", "Green Day", 300); 
		
		
	} 
	
} 
		
		
public class song {
		
// Song Object 
	
private String title; 
	
private String artist; 
	
private int length; } 
		
	
