// Working with Math and Numbers // 

public class App {
	public static void main(String[] args) {
		
		// you can add, subtract, multiply and even divide in the System.out.println() method //
		
	System.out.println((3 - 4));  // output will be -1 }
	
}
} 

		// you can divde integers and get an integer answer back not a decimals 
		
		// if you perform answer using int and double, u will get back a double answer 
		

// just like python, you can ask to return the max and min functions 

System.out.println(math.min(2,6));  Output: 2
