
// Getting user input 

//step 1: import scanner into Java
// Step 2: create new scanner
// Step 3: Ask user for their input

import java.util.Scanner; 


public class App {
	public static void main(String[] args) { 
	
	Scanner KeyboardInput = new Scanner(System.in) 
	
	<Scanner> <Name of Scanner> = new <scanner(System.in) 
	
	System.out.print("Enter your name: ");
	String name = KeyboardInput.nextLine(); // this will grab the value the user entered by acessing this variable
	System.out.println("Hey" + name + "!"); 
	
	// to print out their name
	System.out.print("Enter your age: "); 
	int age = KeyboardInput.nextInt(); // tells java to grab the next input and turn it into Integer
	
	System.out.print("Hey" + name + "! You are " + age + " years old!"); 
	
	}
} 
