
// Return Statments in Java 


// What is the purpose of return statmeents ? // 

	// All methods or functions to give us information after we call them 
	
	public class App {
		
		public static void main(String [] args) { 
		
		
		} 
		
	
	// now we that we want to return something, we can no longer put "void" in the decleation of our methods
	
	// instead of void, you want to put whatever data type you want to return 
	
	// public static <data type you want to return> <name of method/function> ( < data type of parameter > <name of paramter> ) 
	
	
	public static int cube(int numberToCube) {
		return (numberToCube*numberToCube*numberToCube);  } // function takes in a number and cubes it 
		
		
		// then we can call this "numberToCube" function in our main method 
		
	class TestCode {

    public static int cube(int numberToCube) {
        return (numberToCube * numberToCube * numberToCube);
    } // function takes in a number and cubes it


    // then we can call this "numberToCube" function in our main method

    public static void main(String[] args) {

        System.out.print(cube(3)); // need to use print function to actually display file on screen 
    }
}


		// this will output "27" // 
		
		
	
// we can also store the output of our function 

class app {
	
	  public static int cube(int numberToCube) {
        return (numberToCube * numberToCube * numberToCube);
    }

    public static void main(String[] args) {

        int result = cube(2);  // store the output of our function in a variable  

        System.out.print(result); 
    }
}

// this will output 8 

// Note: When you use a return statmenet, you exit out the method and you never get code execuated 



// we can also do the same thing with a string and boolean 


class App {
	
	  public static String cube(int numberToCube) {
        return "Returned Value"; }

    // then we can call this "numberToCube" function in our main method

    public static void main(String[] args) {

        String result = cube(3);

        System.out.print(result); 
    }
}


class TestCode {

    public static boolean cube(int numberToCube) {
        return true; }

    // then we can call this "numberToCube" function in our main method

    public static void main(String[] args) {

        boolean result = cube(3);

        System.out.print(result);
    }
}
