
// If statements in Java 

// a block of code that does something if something else meets the conditon specified 

// sekeleton of "If statements" 

///    if ( < condition goes here> ) { 

///    			<line of code to execuate goes here > } 


// else sekeleton 

			// else {
				
			// 			code to excuate here for else conditon } 			


public class App {
	
	public static void main (String [] args) {
		boolean isMale = true; 
		
		
		if (isMale) { 
			
		System.out.println("You are Male!"); } 
		
		else {
	System.out.println("You are not Male!"); 
	
	} }
} 
		


// and opreator in Java can also be used in if statmenets 


// and opreator in Java can be represented by using "&&" 

// you can also use the "or opreator" which is " || " 


class TestCode {


    public static void main(String[] args) {
        boolean isMale = true;
        boolean isTall = true;


        if (isMale && isTall) {
			
			// using the "or" opreator would look like this if (isMale || isTall) {} 

            System.out.println("You are Male and you are tall");
        } else {
            System.out.println("You are not Male!");
        }
    }
}


// you can also use the "is not" symbol in java 

	if (isMale && !isTall) { // we can read the follow statment as if isMale & is Not Tall 
	
	
	
// we can also use the "else if" condition within our if statmenet 


	else if (isMale || isTall) {
		
	// do something } 
	
// Skeleton else if ( < condition goes here > ) {
	
// 		code to execuate goes here } 

	} 
	
	} 
	
	// we can only use if and else once but else if can be used for as many times as we want 
	
	


