//Types of Data in Java


 String phrase = "To be or not to be"; 
 
 // whole numbers are integers
 
 int Age = 8; 
 
 //deciamls are doubles or floats 
 
 float gpa = 3.5; 
 double gpa = 3.5; //double is more common 
 
 // character 
 
 char Grade = 'A' //use single qoutatation marks for character
 // can only store one character 
 
 
 //boolean: True or False ValueBase
 
 boolean isYoung = True; 
 
